### ISSUE TITLE
It doesn't work well, blank lines still remain

### ISSUE THREAD

**Issue by pakchoidora** [celsomiranda/hexo-beautify#1]
config like below:

    beautify:
      types:
        - html
        - css
        - js
      exclude:
        - '*.min.css'
        - '*.min.js'
      html:
        'indent_inner_html': false
        'indent_size': 2
        'indent_with_tabs': false
        # (...)
      css:
        'indent_size': 2
        'newline_between_rules': true
        'indent_with_tabs': false
        # (...)
      js:
        'indent_size': 2
        'indent_with_tabs': false
        # (...)

**Comment by celsomiranda** [comment]
That is just an example.

On the README it says that for more options you [should check this page](https://github.com/beautify-web/js-beautify/blob/master/README.md).

And you can use it without a config for a sensible defaults.
